### ISSUE TITLE
Add video/picture editing feature

### ISSUE THREAD

**Issue by ugoi** [ugoi/Camagru#5]
Estimated time: 8 story points

**Comment by ugoi** [comment]
#TODO
FRONTEND:
- [ ] add title to html head tag
- [ ] add styling (css)
- [ ] add sidebar with recently taken pictures
- [ ] change button from submit to publish after submission of media
- [ ] redirect to gallery after publishing

**Comment by ugoi** [comment]
Plan:
Friday:
-Improve css and add gallery feature

Saturday:
-Add email verification and password reset feature 

Sunday:
-Dockerize everything in 2 containers

Monday: 
-Manual testing and css improvements
